// SPDX-License-Identifier: GPL-3.0-only
// Copyright (C) 2026 Didier Moraine
package dev.pilotlog.ui.theme

import androidx.compose.ui.graphics.Color

// ── Aviation palette: deep sky blue primary, twilight indigo, amber instrument accent ──

// Light
val md_primary            = Color(0xFF1B5E9B)
val md_onPrimary          = Color(0xFFFFFFFF)
val md_primaryContainer   = Color(0xFFD2E4FF)
val md_onPrimaryContainer = Color(0xFF001C39)
val md_secondary          = Color(0xFF8A5100)   // amber / instrument
val md_onSecondary        = Color(0xFFFFFFFF)
val md_secondaryContainer = Color(0xFFFFDCBA)
val md_onSecondaryContainer = Color(0xFF2C1600)
val md_tertiary           = Color(0xFF455A93)   // twilight indigo
val md_onTertiary         = Color(0xFFFFFFFF)
val md_tertiaryContainer  = Color(0xFFDBE1FF)
val md_onTertiaryContainer = Color(0xFF00164E)
val md_background         = Color(0xFFFAF9FD)
val md_onBackground       = Color(0xFF1A1C1E)
val md_surface            = Color(0xFFFAF9FD)
val md_onSurface          = Color(0xFF1A1C1E)
val md_surfaceVariant     = Color(0xFFDFE2EB)
val md_onSurfaceVariant   = Color(0xFF43474E)
val md_outline            = Color(0xFF73777F)
val md_outlineVariant     = Color(0xFFC3C7CF)
val md_surfaceContainerLowest  = Color(0xFFFFFFFF)
val md_surfaceContainerLow     = Color(0xFFF3F3FA)
val md_surfaceContainer        = Color(0xFFEEEDF4)
val md_surfaceContainerHigh    = Color(0xFFE8E7EF)
val md_surfaceContainerHighest = Color(0xFFE2E2E9)
val md_error              = Color(0xFFBA1A1A)
val md_onError            = Color(0xFFFFFFFF)
val md_errorContainer     = Color(0xFFFFDAD6)
val md_onErrorContainer   = Color(0xFF410002)

// Dark (cockpit at night)
val md_primary_d            = Color(0xFFA1C9FF)
val md_onPrimary_d          = Color(0xFF003259)
val md_primaryContainer_d   = Color(0xFF00497E)
val md_onPrimaryContainer_d = Color(0xFFD2E4FF)
val md_secondary_d          = Color(0xFFFFB960)
val md_onSecondary_d        = Color(0xFF4A2800)
val md_secondaryContainer_d = Color(0xFF693C00)
val md_onSecondaryContainer_d = Color(0xFFFFDCBA)
val md_tertiary_d           = Color(0xFFB4C5FF)
val md_onTertiary_d         = Color(0xFF132C62)
val md_tertiaryContainer_d  = Color(0xFF2D437A)
val md_onTertiaryContainer_d = Color(0xFFDBE1FF)
val md_background_d         = Color(0xFF111417)
val md_onBackground_d       = Color(0xFFE2E2E6)
val md_surface_d            = Color(0xFF111417)
val md_onSurface_d          = Color(0xFFE2E2E6)
val md_surfaceVariant_d     = Color(0xFF43474E)
val md_onSurfaceVariant_d   = Color(0xFFC3C7CF)
val md_outline_d            = Color(0xFF8D9199)
val md_outlineVariant_d     = Color(0xFF43474E)
val md_surfaceContainerLowest_d  = Color(0xFF0C0F11)
val md_surfaceContainerLow_d     = Color(0xFF191C20)
val md_surfaceContainer_d        = Color(0xFF1D2024)
val md_surfaceContainerHigh_d    = Color(0xFF272A2E)
val md_surfaceContainerHighest_d = Color(0xFF323539)
val md_error_d              = Color(0xFFFFB4AB)
val md_onError_d            = Color(0xFF690005)
val md_errorContainer_d     = Color(0xFF93000A)
val md_onErrorContainer_d   = Color(0xFFFFDAD6)
